export const endpoints = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    logoutAll: '/auth/logout-all',
    refresh: '/auth/refresh-token',
    forgotPassword: '/auth/forgot-password',
    resetPassword: (token) => `/auth/reset-password/${token}`,
    verifyEmail: (token) => `/auth/verify-email/${token}`,
    resendVerification: '/auth/resend-verification',
    changePassword: '/auth/change-password',
    sessions: '/auth/sessions',
    revokeSession: (id) => `/auth/sessions/${id}`,
  },
  users: {
    me: '/users/me',
    preferences: '/users/me/preferences',
    avatar: '/users/me/avatar',
  },
  projects: {
    root: '/projects',
    stats: '/projects/stats',
    bookmarks: '/projects/bookmarks',
    publicList: '/projects/public',
    byId: (id) => `/projects/${id}`,
    bySlug: (slug) => `/projects/slug/${slug}`,
    restore: (id) => `/projects/${id}/restore`,
    duplicate: (id) => `/projects/${id}/duplicate`,
    bookmark: (id) => `/projects/${id}/bookmark`,
    cover: (id) => `/projects/${id}/cover`,
    visibility: (id) => `/projects/${id}/visibility`,
    status: (id) => `/projects/${id}/status`,
    export: (id) => `/projects/${id}/export`,
    history: (id) => `/projects/${id}/history`,
  },
  generation: {
    start: (projectId) => `/projects/${projectId}/generate`,
    all: (projectId) => `/projects/${projectId}/generate/all`,
    retry: (projectId, type) => `/projects/${projectId}/generate/${type}/retry`,
    status: (projectId, jobId) => `/projects/${projectId}/generate/status/${jobId}`,
    stream: (projectId, jobId) => `/projects/${projectId}/generate/status/${jobId}/stream`,
    cancel: (projectId, jobId) => `/projects/${projectId}/generate/status/${jobId}`,
  },
  artifacts: {
    list: (projectId) => `/projects/${projectId}/artifacts`,
    byType: (projectId, type) => `/projects/${projectId}/artifacts/${type}`,
    versions: (projectId, type) => `/projects/${projectId}/artifacts/${type}/versions`,
    restore: (projectId, type, version) => `/projects/${projectId}/artifacts/${type}/restore/${version}`,
  },
  diagrams: {
    list: (projectId) => `/projects/${projectId}/diagrams`,
    byType: (projectId, type) => `/projects/${projectId}/diagrams/${type}`,
    generate: (projectId, type) => `/projects/${projectId}/diagrams/${type}/generate`,
  },
  meta: { constants: '/meta/constants' },
  health: '/health',
};

export default endpoints;
