/**
 * Public entry point to the AI subsystem.
 *
 * Responsibilities: quota, cache, ordering, enqueue, status. It orchestrates —
 * it does not know how any individual module is generated. That is the
 * generators' job, reached only through the registry.
 */

import { createJobId } from '../../utils/slug.util.js';
import ApiError from '../../utils/ApiError.js';
import logger from '../../config/logger.js';
import { artifactRepository } from '../../repositories/artifact.repository.js';
import { projectRepository } from '../../repositories/project.repository.js';
import { notificationRepository } from '../../repositories/notification.repository.js';
import { getGenerator, sortByDependencies, getImplementedTypes } from './GeneratorRegistry.js';
import { generationQueue } from './GenerationQueue.js';
import { GENERATION_STATUS, PROJECT_STATUS, JOB_STATUS } from '../../../../shared/constants/statuses.js';

/** Rough per-module wall-clock estimate for the client's progress copy. */
const SECONDS_PER_MODULE = 12;

/**
 * Skip modules that are already completed, fresh, and generated by the current
 * prompt version — unless the caller passes force. On a free AI tier this is the
 * difference between a working demo and a quota error.
 */
const filterCacheable = async (projectId, types, force) => {
  if (force) return { toGenerate: types, cached: [] };

  const existing = await artifactRepository.findMany(
    { project: projectId, type: { $in: types } },
    { select: 'type status isStale promptVersion', lean: true }
  );

  const fresh = new Set(
    existing
      .filter((a) => a.status === GENERATION_STATUS.COMPLETED && !a.isStale)
      .map((a) => a.type)
  );

  return {
    toGenerate: types.filter((t) => !fresh.has(t)),
    cached: types.filter((t) => fresh.has(t)),
  };
};

export const startGeneration = async ({ project, user, modules, force = false }) => {
  const unknown = modules.filter((m) => !getImplementedTypes().includes(m));
  if (unknown.length) {
    throw ApiError.badRequest(
      `These modules are not implemented yet: ${unknown.join(', ')}. Available: ${getImplementedTypes().join(', ')}`
    );
  }

  const { toGenerate, cached } = await filterCacheable(project._id, modules, force);

  if (!toGenerate.length) {
    return {
      jobId: null,
      cached,
      modules: [],
      message: 'All requested modules are already up to date.',
    };
  }

  const orderedTypes = sortByDependencies(toGenerate);
  const jobId = createJobId();

  // Rows exist as "queued" BEFORE the response returns, so a client that polls
  // immediately always sees a consistent state.
  await Promise.all(
    orderedTypes.map((type) => artifactRepository.upsertQueued(project._id, type, jobId))
  );

  await projectRepository.updateById(project._id, { status: PROJECT_STATUS.GENERATING });

  generationQueue.enqueueBatch({
    jobId,
    orderedTypes,
    runner: (type) => getGenerator(type).run({ project, user, jobId }),
    onComplete: async (job) => {
      const failed = job.modules.filter((m) => m.status === GENERATION_STATUS.FAILED).length;
      const succeeded = job.modules.length - failed;

      await projectRepository.updateById(project._id, {
        status: succeeded > 0 ? PROJECT_STATUS.READY : PROJECT_STATUS.DRAFT,
      });

      await notificationRepository.create({
        user: user._id,
        type: failed === 0 ? 'generation_completed' : 'generation_failed',
        title: failed === 0 ? 'Generation complete' : 'Generation finished with errors',
        message:
          failed === 0
            ? `All ${succeeded} module(s) generated for "${project.title}".`
            : `${succeeded} module(s) generated, ${failed} failed for "${project.title}".`,
        link: `/projects/${project._id}`,
        metadata: { projectId: project._id, jobId },
      });

      logger.info(`Job ${jobId} finished: ${succeeded} ok, ${failed} failed`);
    },
  });

  return {
    jobId,
    cached,
    modules: orderedTypes.map((type, index) => ({
      type,
      status: 'queued',
      position: index + 1,
      dependsOn: getGenerator(type).dependsOn.filter((d) => orderedTypes.includes(d)),
    })),
    estimatedSeconds: orderedTypes.length * SECONDS_PER_MODULE,
    creditsReserved: orderedTypes.length,
    creditsRemaining: Math.max(user.aiCredits.limit - user.aiCredits.used - orderedTypes.length, 0),
  };
};

export const generateAll = ({ project, user, force }) =>
  startGeneration({ project, user, modules: getImplementedTypes(), force });

export const retryModule = ({ project, user, type }) =>
  startGeneration({ project, user, modules: [type], force: true });

/**
 * Job status.
 *
 * Reads live queue state when available and falls back to the artifact rows,
 * which are durable. This is what makes status survive a server restart: the
 * in-memory job map is a cache, not the source of truth.
 */
export const getJobStatus = async (projectId, jobId) => {
  const live = generationQueue.getJob(jobId);
  const persisted = await artifactRepository.findByJobId(jobId);

  if (!live && !persisted.length) throw ApiError.notFound('Generation job');

  const modules = live
    ? live.modules.map((m) => {
        const row = persisted.find((p) => p.type === m.type);
        return { ...m, version: row?.version, error: m.error ?? row?.error?.message };
      })
    : persisted.map((p) => ({
        type: p.type,
        status: p.status,
        version: p.version,
        durationMs: p.generationMeta?.latencyMs,
        error: p.error?.message,
      }));

  const finished = modules.filter((m) =>
    [GENERATION_STATUS.COMPLETED, GENERATION_STATUS.FAILED, 'cancelled'].includes(m.status)
  ).length;

  const failed = modules.filter((m) => m.status === GENERATION_STATUS.FAILED).length;

  const overallStatus =
    live?.status ??
    (finished < modules.length
      ? JOB_STATUS.RUNNING
      : failed === 0
        ? JOB_STATUS.COMPLETED
        : failed === modules.length
          ? JOB_STATUS.FAILED
          : JOB_STATUS.PARTIAL);

  return {
    jobId,
    overallStatus,
    progress: modules.length ? Math.round((finished / modules.length) * 100) : 0,
    startedAt: live?.startedAt,
    finishedAt: live?.finishedAt,
    modules,
  };
};

export const cancelJob = (jobId) => {
  const cancelled = generationQueue.cancel(jobId);
  if (!cancelled) throw ApiError.notFound('Generation job');
  return { jobId, cancelled: true };
};

export const getQueueStats = () => generationQueue.stats;

export default {
  startGeneration,
  generateAll,
  retryModule,
  getJobStatus,
  cancelJob,
  getQueueStats,
};
